# Assume the database is ready
server:
  port: ${PORT:8102}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true
      
  app:
    data-provider:
      domain: ${DATA_PROVIDER_DOMAIN:localhost}
      port: ${DATA_PROVIDER_PORT:8101}

