# Assume the database is ready
server:
    port: ${PORT:8101}


api:
  finnhub:
    domain: "finnhub.io"
    vers: "api/v1"
    endpoints:
      chart: "stock/profile2"
    key: ${FINNHUB_API_KEY}






